[package]
name = "timer-tui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.34"
crossterm = "0.27.0"
ratatui = "0.26.1"
regex = "1.10.3"
